// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9GQgG9zO7h9-sN_9_FPy1C3D940r3Kls',
    appId: '1:1034467644370:web:8f49134e49a8f70a99ee0b',
    messagingSenderId: '1034467644370',
    projectId: 'tunisiaed-811f6',
    authDomain: 'tunisiaed-811f6.firebaseapp.com',
    storageBucket: 'tunisiaed-811f6.firebasestorage.app',
    measurementId: 'G-CS2XVJ0EVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbVE3IVlhG5vsKJdHTXw3yEGQwp05VlBs',
    appId: '1:1034467644370:android:f6ed3a86371ee6d799ee0b',
    messagingSenderId: '1034467644370',
    projectId: 'tunisiaed-811f6',
    storageBucket: 'tunisiaed-811f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOOH4tz0tJelbg6P2KWvqL74EVw-DJEv4',
    appId: '1:1034467644370:ios:6987261db7136aff99ee0b',
    messagingSenderId: '1034467644370',
    projectId: 'tunisiaed-811f6',
    storageBucket: 'tunisiaed-811f6.firebasestorage.app',
    iosClientId: '1034467644370-113q2vpo3fhrl83g5droj22qo8l7qama.apps.googleusercontent.com',
    iosBundleId: 'com.tunisiaed.eplatform',
  );
}
