// System course chapters
// Organized by courseId for easy mapping

export const SYSTEM_CHAPTERS = {
  // Web Development Bootcamp Chapters
  'sys-course-001': [
    {
      chapterId: 'sys-chapter-001-1',
      courseId: 'sys-course-001',
      title: 'HTML & CSS Fundamentals',
      description: 'Learn the building blocks of web development. Master HTML5 semantic elements, CSS3 styling, Flexbox, and Grid layout systems.',
      order: 1,
      duration: 8,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-001-2',
      courseId: 'sys-course-001',
      title: 'JavaScript Essentials',
      description: 'Dive into JavaScript programming. Variables, functions, arrays, objects, DOM manipulation, and ES6+ features.',
      order: 2,
      duration: 10,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-001-3',
      courseId: 'sys-course-001',
      title: 'React Fundamentals',
      description: 'Build modern user interfaces with React. Components, props, state, hooks, and React Router.',
      order: 3,
      duration: 12,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-001-4',
      courseId: 'sys-course-001',
      title: 'Node.js & Express Backend',
      description: 'Create server-side applications with Node.js and Express. RESTful APIs, middleware, and authentication.',
      order: 4,
      duration: 10,
      isSystemContent: true,
    },
  ],

  // Python for Data Science Chapters
  'sys-course-002': [
    {
      chapterId: 'sys-chapter-002-1',
      courseId: 'sys-course-002',
      title: 'Python Programming Basics',
      description: 'Master Python fundamentals. Variables, data types, control flow, functions, and object-oriented programming.',
      order: 1,
      duration: 8,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-002-2',
      courseId: 'sys-course-002',
      title: 'NumPy & Pandas for Data Manipulation',
      description: 'Learn data manipulation with NumPy arrays and Pandas DataFrames. Data cleaning, filtering, and aggregation.',
      order: 2,
      duration: 10,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-002-3',
      courseId: 'sys-course-002',
      title: 'Data Visualization with Matplotlib',
      description: 'Create compelling visualizations. Line plots, bar charts, scatter plots, histograms, and customization.',
      order: 3,
      duration: 6,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-002-4',
      courseId: 'sys-course-002',
      title: 'Machine Learning with Scikit-learn',
      description: 'Introduction to machine learning algorithms. Regression, classification, clustering, and model evaluation.',
      order: 4,
      duration: 6,
      isSystemContent: true,
    },
  ],

  // UI/UX Design Masterclass Chapters
  'sys-course-003': [
    {
      chapterId: 'sys-chapter-003-1',
      courseId: 'sys-course-003',
      title: 'Design Thinking & User Research',
      description: 'Understand users deeply. User interviews, personas, journey mapping, and empathy-driven design.',
      order: 1,
      duration: 6,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-003-2',
      courseId: 'sys-course-003',
      title: 'Wireframing & Prototyping',
      description: 'Create low and high-fidelity wireframes. Learn rapid prototyping techniques and user testing.',
      order: 2,
      duration: 7,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-003-3',
      courseId: 'sys-course-003',
      title: 'Visual Design Principles',
      description: 'Master typography, color theory, spacing, hierarchy, and composition for beautiful interfaces.',
      order: 3,
      duration: 6,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-003-4',
      courseId: 'sys-course-003',
      title: 'Figma Mastery',
      description: 'Complete Figma workflow. Components, variants, auto-layout, design systems, and collaboration.',
      order: 4,
      duration: 6,
      isSystemContent: true,
    },
  ],

  // Digital Marketing Complete Course Chapters
  'sys-course-004': [
    {
      chapterId: 'sys-chapter-004-1',
      courseId: 'sys-course-004',
      title: 'Digital Marketing Fundamentals',
      description: 'Overview of digital marketing channels. Strategy, goals, metrics, and customer acquisition.',
      order: 1,
      duration: 5,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-004-2',
      courseId: 'sys-course-004',
      title: 'SEO & Content Marketing',
      description: 'Master search engine optimization. Keyword research, on-page SEO, link building, and content strategy.',
      order: 2,
      duration: 6,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-004-3',
      courseId: 'sys-course-004',
      title: 'Social Media Marketing',
      description: 'Grow your audience on Facebook, Instagram, LinkedIn, and Twitter. Content creation and engagement strategies.',
      order: 3,
      duration: 5,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-004-4',
      courseId: 'sys-course-004',
      title: 'Paid Advertising (Google & Facebook Ads)',
      description: 'Run profitable ad campaigns. Ad creation, targeting, bidding strategies, and conversion optimization.',
      order: 4,
      duration: 4,
      isSystemContent: true,
    },
  ],

  // JavaScript Algorithms & Data Structures Chapters
  'sys-course-005': [
    {
      chapterId: 'sys-chapter-005-1',
      courseId: 'sys-course-005',
      title: 'Big O Notation & Complexity Analysis',
      description: 'Understand algorithm efficiency. Time and space complexity, best/worst case scenarios.',
      order: 1,
      duration: 6,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-005-2',
      courseId: 'sys-course-005',
      title: 'Arrays, Strings & Hash Tables',
      description: 'Master fundamental data structures. Array manipulation, string algorithms, and hash table implementation.',
      order: 2,
      duration: 8,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-005-3',
      courseId: 'sys-course-005',
      title: 'Linked Lists, Stacks & Queues',
      description: 'Linear data structures in depth. Implementation, traversal, and common interview problems.',
      order: 3,
      duration: 8,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-005-4',
      courseId: 'sys-course-005',
      title: 'Trees, Graphs & Advanced Algorithms',
      description: 'Complex data structures and algorithms. Binary trees, BST, graph traversal, dynamic programming.',
      order: 4,
      duration: 13,
      isSystemContent: true,
    },
  ],

  // Business Strategy & Entrepreneurship Chapters
  'sys-course-006': [
    {
      chapterId: 'sys-chapter-006-1',
      courseId: 'sys-course-006',
      title: 'Business Model Canvas',
      description: 'Design your business model. Value proposition, customer segments, revenue streams, and key resources.',
      order: 1,
      duration: 7,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-006-2',
      courseId: 'sys-course-006',
      title: 'Market Research & Validation',
      description: 'Validate your business idea. Market analysis, competitor research, and customer validation techniques.',
      order: 2,
      duration: 7,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-006-3',
      courseId: 'sys-course-006',
      title: 'Funding & Financial Planning',
      description: 'Secure funding for your startup. Bootstrapping, angel investors, VC funding, and financial projections.',
      order: 3,
      duration: 7,
      isSystemContent: true,
    },
    {
      chapterId: 'sys-chapter-006-4',
      courseId: 'sys-course-006',
      title: 'Scaling & Growth Strategies',
      description: 'Grow your business sustainably. Hiring, operations, marketing, and expansion strategies.',
      order: 4,
      duration: 7,
      isSystemContent: true,
    },
  ],
};
