// System-provided courses data
// These courses are hardcoded and seeded into Firestore with isSystemCourse flag
// They behave exactly like instructor courses for students

export const SYSTEM_INSTRUCTOR_UID = 'system_instructor';
export const SYSTEM_INSTRUCTOR_NAME = 'E-Learning Academy';

export const SYSTEM_INSTRUCTOR_PROFILE = {
  uid: SYSTEM_INSTRUCTOR_UID,
  name: SYSTEM_INSTRUCTOR_NAME,
  email: 'system@tunisiaed.com',
  role: 'instructor',
  avatar: 'https://firebasestorage.googleapis.com/v0/b/tunisiaed-811f6.appspot.com/o/system%2Finstructor-avatar.png?alt=media',
  bio: 'Official courses curated by E-Learning Academy. High-quality content designed by industry experts.',
  signature: 'https://firebasestorage.googleapis.com/v0/b/tunisiaed-811f6.appspot.com/o/system%2Finstructor-signature.png?alt=media',
  createdAt: new Date('2024-01-01'),
  isSystemAccount: true,
  loginDisabled: true, // Cannot be used to sign in
};

export const SYSTEM_COURSES = [
  {
    courseId: 'sys-course-001',
    title: 'Complete Web Development Bootcamp',
    description: 'Master HTML, CSS, JavaScript, React, Node.js, and MongoDB. Build 10+ real-world projects and become a full-stack developer.',
    instructorId: SYSTEM_INSTRUCTOR_UID,
    instructorName: SYSTEM_INSTRUCTOR_NAME,
    category: 'Programming',
    level: 'beginner',
    price: 0, // FREE COURSE
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
    duration: 40,
    enrolledCount: 0,
    rating: 0,
    isSystemCourse: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    courseId: 'sys-course-002',
    title: 'Python for Data Science',
    description: 'Learn Python programming with NumPy, Pandas, Matplotlib, and Scikit-learn. Real data analysis projects included.',
    instructorId: SYSTEM_INSTRUCTOR_UID,
    instructorName: SYSTEM_INSTRUCTOR_NAME,
    category: 'Programming',
    level: 'intermediate',
    price: 0, // FREE COURSE
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800',
    duration: 30,
    enrolledCount: 0,
    rating: 0,
    isSystemCourse: true,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    courseId: 'sys-course-003',
    title: 'UI/UX Design Masterclass',
    description: 'Master Figma, design thinking, user research, wireframing, and prototyping. Create stunning user interfaces.',
    instructorId: SYSTEM_INSTRUCTOR_UID,
    instructorName: SYSTEM_INSTRUCTOR_NAME,
    category: 'Design',
    level: 'beginner',
    price: 199,
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
    duration: 25,
    enrolledCount: 0,
    rating: 0,
    isSystemCourse: true,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    courseId: 'sys-course-004',
    title: 'Digital Marketing Complete Course',
    description: 'SEO, social media marketing, email marketing, Google Ads, Facebook Ads, and analytics. Grow your business online.',
    instructorId: SYSTEM_INSTRUCTOR_UID,
    instructorName: SYSTEM_INSTRUCTOR_NAME,
    category: 'Marketing',
    level: 'beginner',
    price: 179,
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    duration: 20,
    enrolledCount: 0,
    rating: 0,
    isSystemCourse: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    courseId: 'sys-course-005',
    title: 'JavaScript Algorithms & Data Structures',
    description: 'Master coding interviews with algorithms, data structures, Big O notation, and problem-solving patterns.',
    instructorId: SYSTEM_INSTRUCTOR_UID,
    instructorName: SYSTEM_INSTRUCTOR_NAME,
    category: 'Programming',
    level: 'advanced',
    price: 299,
    thumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800',
    duration: 35,
    enrolledCount: 0,
    rating: 0,
    isSystemCourse: true,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    courseId: 'sys-course-006',
    title: 'Business Strategy & Entrepreneurship',
    description: 'Learn how to start and grow a successful business. Business models, funding, marketing, and scaling strategies.',
    instructorId: SYSTEM_INSTRUCTOR_UID,
    instructorName: SYSTEM_INSTRUCTOR_NAME,
    category: 'Business',
    level: 'intermediate',
    price: 229,
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
    duration: 28,
    enrolledCount: 0,
    rating: 0,
    isSystemCourse: true,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
];
