// System course lessons
// Organized by chapterId for easy mapping

export const SYSTEM_LESSONS = {
  // HTML & CSS Fundamentals Lessons
  'sys-chapter-001-1': [
    {
      lessonId: 'sys-lesson-001-1-1',
      chapterId: 'sys-chapter-001-1',
      courseId: 'sys-course-001',
      title: 'HTML5 Structure & Semantic Elements',
      description: 'Learn HTML document structure, semantic tags like header, nav, main, article, section, and footer.',
      content: 'Master the building blocks of web pages with HTML5 semantic elements that improve accessibility and SEO.',
      videoUrl: 'https://www.youtube.com/watch?v=UB1O30fR-EE',
      duration: 45,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-1-2',
      chapterId: 'sys-chapter-001-1',
      courseId: 'sys-course-001',
      title: 'CSS3 Styling Basics',
      description: 'Selectors, properties, values, box model, colors, typography, and responsive units.',
      content: 'Style your HTML with CSS3. Understand the cascade, specificity, and modern CSS properties.',
      videoUrl: 'https://www.youtube.com/watch?v=1Rs2ND1ryYc',
      duration: 50,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-1-3',
      chapterId: 'sys-chapter-001-1',
      courseId: 'sys-course-001',
      title: 'Flexbox Layout System',
      description: 'Master Flexbox for one-dimensional layouts. Flex containers, items, alignment, and responsiveness.',
      content: 'Create flexible and responsive layouts with CSS Flexbox. Learn flex-direction, justify-content, align-items.',
      videoUrl: 'https://www.youtube.com/watch?v=fYq5PXgSsbE',
      duration: 40,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-1-4',
      chapterId: 'sys-chapter-001-1',
      courseId: 'sys-course-001',
      title: 'CSS Grid Layout',
      description: 'Two-dimensional layouts with CSS Grid. Grid template, areas, and responsive design patterns.',
      content: 'Build complex layouts easily with CSS Grid. Understand grid lines, tracks, and areas.',
      videoUrl: 'https://www.youtube.com/watch?v=EiNiSFIPIQE',
      duration: 45,
      order: 4,
      isSystemContent: true,
    },
  ],

  // JavaScript Essentials Lessons
  'sys-chapter-001-2': [
    {
      lessonId: 'sys-lesson-001-2-1',
      chapterId: 'sys-chapter-001-2',
      courseId: 'sys-course-001',
      title: 'JavaScript Fundamentals',
      description: 'Variables (let, const, var), data types, operators, and type coercion.',
      content: 'Start your JavaScript journey with core programming concepts and syntax.',
      videoUrl: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
      duration: 60,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-2-2',
      chapterId: 'sys-chapter-001-2',
      courseId: 'sys-course-001',
      title: 'Functions & Scope',
      description: 'Function declarations, expressions, arrow functions, scope, closures, and higher-order functions.',
      content: 'Master JavaScript functions and understand how scope and closures work.',
      videoUrl: 'https://www.youtube.com/watch?v=gigtS_5KOqo',
      duration: 55,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-2-3',
      chapterId: 'sys-chapter-001-2',
      courseId: 'sys-course-001',
      title: 'Arrays & Objects',
      description: 'Array methods (map, filter, reduce), object manipulation, destructuring, and spread operator.',
      content: 'Work with JavaScript data structures. Master array and object manipulation techniques.',
      videoUrl: 'https://www.youtube.com/watch?v=R8rmfD9Y5-c',
      duration: 50,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-2-4',
      chapterId: 'sys-chapter-001-2',
      courseId: 'sys-course-001',
      title: 'DOM Manipulation',
      description: 'Select elements, modify content, handle events, and create dynamic web pages.',
      content: 'Bring your web pages to life by manipulating the Document Object Model with JavaScript.',
      videoUrl: 'https://www.youtube.com/watch?v=5fb2aPlgoys',
      duration: 45,
      order: 4,
      isSystemContent: true,
    },
  ],

  // React Fundamentals Lessons
  'sys-chapter-001-3': [
    {
      lessonId: 'sys-lesson-001-3-1',
      chapterId: 'sys-chapter-001-3',
      courseId: 'sys-course-001',
      title: 'React Components & JSX',
      description: 'Learn React components, JSX syntax, props, and component composition.',
      content: 'Build reusable UI components with React. Understand the component lifecycle and JSX.',
      videoUrl: 'https://www.youtube.com/watch?v=w7ejDZ8SWv8',
      duration: 55,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-3-2',
      chapterId: 'sys-chapter-001-3',
      courseId: 'sys-course-001',
      title: 'State & useState Hook',
      description: 'Manage component state with useState. State updates, re-renders, and immutability.',
      content: 'Make your components interactive with React state management using hooks.',
      videoUrl: 'https://www.youtube.com/watch?v=O6P86uwfdR0',
      duration: 50,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-3-3',
      chapterId: 'sys-chapter-001-3',
      courseId: 'sys-course-001',
      title: 'useEffect & Side Effects',
      description: 'Handle side effects with useEffect. API calls, subscriptions, and cleanup functions.',
      content: 'Fetch data and manage side effects in React components with the useEffect hook.',
      videoUrl: 'https://www.youtube.com/watch?v=0ZJgIjIuY7U',
      duration: 55,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-3-4',
      chapterId: 'sys-chapter-001-3',
      courseId: 'sys-course-001',
      title: 'React Router & Navigation',
      description: 'Implement client-side routing with React Router. Routes, links, and navigation patterns.',
      content: 'Build multi-page React applications with React Router for seamless navigation.',
      videoUrl: 'https://www.youtube.com/watch?v=Law7wfdg_ls',
      duration: 50,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Node.js & Express Backend Lessons
  'sys-chapter-001-4': [
    {
      lessonId: 'sys-lesson-001-4-1',
      chapterId: 'sys-chapter-001-4',
      courseId: 'sys-course-001',
      title: 'Node.js Fundamentals',
      description: 'Node.js runtime, modules, npm, and asynchronous programming with callbacks and promises.',
      content: 'Build server-side applications with Node.js. Understand the event loop and async patterns.',
      videoUrl: 'https://www.youtube.com/watch?v=TlB_eWDSMt4',
      duration: 55,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-4-2',
      chapterId: 'sys-chapter-001-4',
      courseId: 'sys-course-001',
      title: 'Express.js Server & Routes',
      description: 'Create Express servers, define routes, handle HTTP methods, and structure your backend.',
      content: 'Build RESTful APIs with Express.js. Learn routing, middleware, and request handling.',
      videoUrl: 'https://www.youtube.com/watch?v=L72fhGm1tfE',
      duration: 60,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-4-3',
      chapterId: 'sys-chapter-001-4',
      courseId: 'sys-course-001',
      title: 'MongoDB & Mongoose',
      description: 'Database integration with MongoDB. Schemas, models, CRUD operations, and data validation.',
      content: 'Store and retrieve data with MongoDB and Mongoose ODM for Node.js applications.',
      videoUrl: 'https://www.youtube.com/watch?v=ofme2o29ngU',
      duration: 55,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-001-4-4',
      chapterId: 'sys-chapter-001-4',
      courseId: 'sys-course-001',
      title: 'Authentication & JWT',
      description: 'Implement user authentication with JSON Web Tokens. Registration, login, and protected routes.',
      content: 'Secure your API with JWT-based authentication and authorization patterns.',
      videoUrl: 'https://www.youtube.com/watch?v=mbsmsi7l3r4',
      duration: 50,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Python Programming Basics Lessons (Course 002)
  'sys-chapter-002-1': [
    {
      lessonId: 'sys-lesson-002-1-1',
      chapterId: 'sys-chapter-002-1',
      courseId: 'sys-course-002',
      title: 'Python Syntax & Variables',
      description: 'Python basics: variables, data types, operators, and input/output.',
      content: 'Start programming in Python with core syntax and fundamental concepts.',
      videoUrl: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
      duration: 50,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-002-1-2',
      chapterId: 'sys-chapter-002-1',
      courseId: 'sys-course-002',
      title: 'Control Flow & Loops',
      description: 'If statements, for loops, while loops, and comprehensions.',
      content: 'Control program flow with conditional statements and iteration in Python.',
      videoUrl: 'https://www.youtube.com/watch?v=HZARImviDxg',
      duration: 45,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-002-1-3',
      chapterId: 'sys-chapter-002-1',
      courseId: 'sys-course-002',
      title: 'Functions & Modules',
      description: 'Define functions, parameters, return values, and organize code with modules.',
      content: 'Write reusable code with Python functions and modular programming.',
      videoUrl: 'https://www.youtube.com/watch?v=9Os0o3wzS_I',
      duration: 45,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-002-1-4',
      chapterId: 'sys-chapter-002-1',
      courseId: 'sys-course-002',
      title: 'Object-Oriented Programming',
      description: 'Classes, objects, inheritance, encapsulation, and polymorphism in Python.',
      content: 'Master OOP concepts in Python for building scalable applications.',
      videoUrl: 'https://www.youtube.com/watch?v=Ej_02ICOIgs',
      duration: 60,
      order: 4,
      isSystemContent: true,
    },
  ],

  // NumPy & Pandas for Data Manipulation Lessons
  'sys-chapter-002-2': [
    {
      lessonId: 'sys-lesson-002-2-1',
      chapterId: 'sys-chapter-002-2',
      courseId: 'sys-course-002',
      title: 'NumPy Arrays & Operations',
      description: 'Create and manipulate NumPy arrays. Array operations, indexing, slicing, and broadcasting.',
      content: 'Master numerical computing in Python with NumPy arrays and vectorized operations.',
      videoUrl: 'https://www.youtube.com/watch?v=QUT1VHiLmmI',
      duration: 55,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-002-2-2',
      chapterId: 'sys-chapter-002-2',
      courseId: 'sys-course-002',
      title: 'Pandas DataFrames',
      description: 'Load, explore, and manipulate data with Pandas DataFrames and Series.',
      content: 'Work with structured data using Pandas, the essential data analysis library.',
      videoUrl: 'https://www.youtube.com/watch?v=vmEHCJofslg',
      duration: 60,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-002-2-3',
      chapterId: 'sys-chapter-002-2',
      courseId: 'sys-course-002',
      title: 'Data Cleaning & Preprocessing',
      description: 'Handle missing data, duplicates, data type conversions, and outliers.',
      content: 'Prepare real-world data for analysis with cleaning and preprocessing techniques.',
      videoUrl: 'https://www.youtube.com/watch?v=xi0vhXFPegw',
      duration: 50,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-002-2-4',
      chapterId: 'sys-chapter-002-2',
      courseId: 'sys-course-002',
      title: 'Data Aggregation & Grouping',
      description: 'GroupBy operations, aggregation functions, pivot tables, and merging datasets.',
      content: 'Analyze data efficiently with Pandas grouping and aggregation capabilities.',
      videoUrl: 'https://www.youtube.com/watch?v=txMdrV1Ut64',
      duration: 55,
      order: 4,
      isSystemContent: true,
    },
  ],

  // UI/UX Design Course (Course 003)
  // Design Thinking & User Research Lessons
  'sys-chapter-003-1': [
    {
      lessonId: 'sys-lesson-003-1-1',
      chapterId: 'sys-chapter-003-1',
      courseId: 'sys-course-003',
      title: 'Introduction to Design Thinking',
      description: 'Understand the five stages of design thinking: Empathize, Define, Ideate, Prototype, and Test.',
      content: 'Learn the human-centered design process that helps solve complex problems creatively.',
      videoUrl: 'https://www.youtube.com/watch?v=_r0VX-aU_T8',
      duration: 40,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-1-2',
      chapterId: 'sys-chapter-003-1',
      courseId: 'sys-course-003',
      title: 'User Research Methods',
      description: 'Interviews, surveys, observation, and ethnographic studies to understand user needs.',
      content: 'Conduct effective user research to gather insights and validate design decisions.',
      videoUrl: 'https://www.youtube.com/watch?v=Qq3OiHQ-HCU',
      duration: 45,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-1-3',
      chapterId: 'sys-chapter-003-1',
      courseId: 'sys-course-003',
      title: 'Creating User Personas',
      description: 'Build detailed user personas based on research data to guide design decisions.',
      content: 'Transform research insights into actionable personas representing your target users.',
      videoUrl: 'https://www.youtube.com/watch?v=XnG4c4gXaQY',
      duration: 35,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-1-4',
      chapterId: 'sys-chapter-003-1',
      courseId: 'sys-course-003',
      title: 'User Journey Mapping',
      description: 'Map the complete user experience, identifying pain points and opportunities.',
      content: 'Visualize the user journey to improve touchpoints and create better experiences.',
      videoUrl: 'https://www.youtube.com/watch?v=2W13ext26kQ',
      duration: 40,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Wireframing & Prototyping Lessons
  'sys-chapter-003-2': [
    {
      lessonId: 'sys-lesson-003-2-1',
      chapterId: 'sys-chapter-003-2',
      courseId: 'sys-course-003',
      title: 'Low-Fidelity Wireframing',
      description: 'Sketch basic layouts and user flows using paper prototypes and digital wireframes.',
      content: 'Create quick, iterative wireframes to test ideas before investing in high-fidelity designs.',
      videoUrl: 'https://www.youtube.com/watch?v=qpH7-KFWZRI',
      duration: 45,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-2-2',
      chapterId: 'sys-chapter-003-2',
      courseId: 'sys-course-003',
      title: 'Figma Fundamentals',
      description: 'Master Figma interface, tools, components, and collaborative features.',
      content: 'Learn the industry-standard design tool for creating professional UI designs.',
      videoUrl: 'https://www.youtube.com/watch?v=FTFaQWZBqQ8',
      duration: 50,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-2-3',
      chapterId: 'sys-chapter-003-2',
      courseId: 'sys-course-003',
      title: 'Interactive Prototyping',
      description: 'Build clickable prototypes with interactions, transitions, and animations in Figma.',
      content: 'Bring your designs to life with interactive prototypes for user testing.',
      videoUrl: 'https://www.youtube.com/watch?v=RJPLmEzw4WQ',
      duration: 55,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-2-4',
      chapterId: 'sys-chapter-003-2',
      courseId: 'sys-course-003',
      title: 'Usability Testing',
      description: 'Conduct usability tests, gather feedback, and iterate on your designs.',
      content: 'Validate your designs with real users and improve based on testing insights.',
      videoUrl: 'https://www.youtube.com/watch?v=BrgunwnUys0',
      duration: 45,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Visual Design Principles Lessons
  'sys-chapter-003-3': [
    {
      lessonId: 'sys-lesson-003-3-1',
      chapterId: 'sys-chapter-003-3',
      courseId: 'sys-course-003',
      title: 'Typography & Readability',
      description: 'Font selection, hierarchy, spacing, and creating readable text layouts.',
      content: 'Master typography principles to create clear, accessible, and beautiful text designs.',
      videoUrl: 'https://www.youtube.com/watch?v=sByzHoiYFX0',
      duration: 40,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-3-2',
      chapterId: 'sys-chapter-003-3',
      courseId: 'sys-course-003',
      title: 'Color Theory for UI',
      description: 'Color psychology, palettes, contrast ratios, and accessibility standards (WCAG).',
      content: 'Choose and apply colors effectively to create visually appealing and accessible interfaces.',
      videoUrl: 'https://www.youtube.com/watch?v=KMS3VwGh3HY',
      duration: 45,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-3-3',
      chapterId: 'sys-chapter-003-3',
      courseId: 'sys-course-003',
      title: 'Layout & Grid Systems',
      description: 'Grid-based layouts, spacing systems, and responsive design patterns.',
      content: 'Create organized, scalable layouts using professional grid systems.',
      videoUrl: 'https://www.youtube.com/watch?v=n_V_aLqYPI0',
      duration: 50,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-3-4',
      chapterId: 'sys-chapter-003-3',
      courseId: 'sys-course-003',
      title: 'Design Systems & Components',
      description: 'Build reusable component libraries and maintain design consistency.',
      content: 'Scale your designs efficiently with design systems and component libraries.',
      videoUrl: 'https://www.youtube.com/watch?v=Dtd40cHQQlk',
      duration: 55,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Accessibility & Responsive Design Lessons
  'sys-chapter-003-4': [
    {
      lessonId: 'sys-lesson-003-4-1',
      chapterId: 'sys-chapter-003-4',
      courseId: 'sys-course-003',
      title: 'Web Accessibility Standards',
      description: 'WCAG guidelines, ARIA labels, keyboard navigation, and screen reader compatibility.',
      content: 'Design inclusive interfaces that work for users with disabilities.',
      videoUrl: 'https://www.youtube.com/watch?v=e2nkq3h1P68',
      duration: 50,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-4-2',
      chapterId: 'sys-chapter-003-4',
      courseId: 'sys-course-003',
      title: 'Mobile-First Design',
      description: 'Design for mobile devices first, then scale up to tablets and desktops.',
      content: 'Create responsive designs optimized for mobile users with progressive enhancement.',
      videoUrl: 'https://www.youtube.com/watch?v=0ohtVzCSHqs',
      duration: 45,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-4-3',
      chapterId: 'sys-chapter-003-4',
      courseId: 'sys-course-003',
      title: 'Responsive Breakpoints',
      description: 'Define breakpoints, fluid grids, and flexible images for all screen sizes.',
      content: 'Ensure your designs adapt seamlessly across devices with responsive techniques.',
      videoUrl: 'https://www.youtube.com/watch?v=srvUrASNj0s',
      duration: 40,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-003-4-4',
      chapterId: 'sys-chapter-003-4',
      courseId: 'sys-course-003',
      title: 'Design Handoff to Developers',
      description: 'Prepare design files, specifications, and assets for developer implementation.',
      content: 'Streamline collaboration with developers using proper handoff techniques.',
      videoUrl: 'https://www.youtube.com/watch?v=YJG98zNL9Dc',
      duration: 45,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Digital Marketing Course (Course 004)
  // Social Media Marketing Lessons
  'sys-chapter-004-1': [
    {
      lessonId: 'sys-lesson-004-1-1',
      chapterId: 'sys-chapter-004-1',
      courseId: 'sys-course-004',
      title: 'Social Media Strategy Development',
      description: 'Define goals, target audience, content pillars, and KPIs for social media success.',
      content: 'Build a comprehensive social media strategy aligned with business objectives.',
      videoUrl: 'https://www.youtube.com/watch?v=qJGVMY3Vtu4',
      duration: 45,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-1-2',
      chapterId: 'sys-chapter-004-1',
      courseId: 'sys-course-004',
      title: 'Content Creation & Storytelling',
      description: 'Create engaging content, write compelling captions, and tell brand stories.',
      content: 'Master content creation techniques that resonate with your audience.',
      videoUrl: 'https://www.youtube.com/watch?v=2cdlkH8tXlM',
      duration: 50,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-1-3',
      chapterId: 'sys-chapter-004-1',
      courseId: 'sys-course-004',
      title: 'Facebook & Instagram Marketing',
      description: 'Organic reach strategies, paid ads, Stories, Reels, and Instagram Shopping.',
      content: 'Leverage Facebook and Instagram to grow your audience and drive conversions.',
      videoUrl: 'https://www.youtube.com/watch?v=FKcq3J-h5HU',
      duration: 55,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-1-4',
      chapterId: 'sys-chapter-004-1',
      courseId: 'sys-course-004',
      title: 'TikTok & Short-Form Video',
      description: 'Viral content strategies, TikTok algorithm, trends, and influencer marketing.',
      content: 'Harness the power of short-form video to reach younger demographics.',
      videoUrl: 'https://www.youtube.com/watch?v=wMUfvZPP_W8',
      duration: 45,
      order: 4,
      isSystemContent: true,
    },
  ],

  // SEO & Content Marketing Lessons
  'sys-chapter-004-2': [
    {
      lessonId: 'sys-lesson-004-2-1',
      chapterId: 'sys-chapter-004-2',
      courseId: 'sys-course-004',
      title: 'SEO Fundamentals',
      description: 'Keyword research, on-page SEO, technical SEO, and backlink strategies.',
      content: 'Optimize your website to rank higher in search engines and drive organic traffic.',
      videoUrl: 'https://www.youtube.com/watch?v=DvwS7cV9GmQ',
      duration: 60,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-2-2',
      chapterId: 'sys-chapter-004-2',
      courseId: 'sys-course-004',
      title: 'Content Strategy & Blogging',
      description: 'Create valuable content, editorial calendars, and content distribution strategies.',
      content: 'Attract and retain audiences with strategic, high-quality content marketing.',
      videoUrl: 'https://www.youtube.com/watch?v=2xWU2dia2P0',
      duration: 50,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-2-3',
      chapterId: 'sys-chapter-004-2',
      courseId: 'sys-course-004',
      title: 'Local SEO & Google Business',
      description: 'Optimize for local search, Google My Business, reviews, and local citations.',
      content: 'Dominate local search results and attract nearby customers.',
      videoUrl: 'https://www.youtube.com/watch?v=s1VfFaq8KkI',
      duration: 45,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-2-4',
      chapterId: 'sys-chapter-004-2',
      courseId: 'sys-course-004',
      title: 'Link Building & Authority',
      description: 'Guest posting, outreach strategies, and building domain authority.',
      content: 'Earn high-quality backlinks to boost your search engine rankings.',
      videoUrl: 'https://www.youtube.com/watch?v=G2SUaSKBgqM',
      duration: 50,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Email Marketing & Automation Lessons
  'sys-chapter-004-3': [
    {
      lessonId: 'sys-lesson-004-3-1',
      chapterId: 'sys-chapter-004-3',
      courseId: 'sys-course-004',
      title: 'Email List Building',
      description: 'Lead magnets, opt-in forms, landing pages, and list segmentation strategies.',
      content: 'Build a valuable email list of engaged subscribers.',
      videoUrl: 'https://www.youtube.com/watch?v=n-NjoiR_Nas',
      duration: 45,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-3-2',
      chapterId: 'sys-chapter-004-3',
      courseId: 'sys-course-004',
      title: 'Email Copywriting & Design',
      description: 'Write compelling subject lines, body copy, CTAs, and design responsive emails.',
      content: 'Create emails that get opened, read, and drive action.',
      videoUrl: 'https://www.youtube.com/watch?v=D7uMHxFWKZ8',
      duration: 50,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-3-3',
      chapterId: 'sys-chapter-004-3',
      courseId: 'sys-course-004',
      title: 'Marketing Automation Workflows',
      description: 'Set up automated email sequences, drip campaigns, and behavioral triggers.',
      content: 'Automate your marketing to nurture leads and convert customers efficiently.',
      videoUrl: 'https://www.youtube.com/watch?v=Z-8F6WvXJXY',
      duration: 55,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-3-4',
      chapterId: 'sys-chapter-004-3',
      courseId: 'sys-course-004',
      title: 'Email Analytics & A/B Testing',
      description: 'Track open rates, click rates, conversions, and optimize campaigns with testing.',
      content: 'Measure and improve email performance with data-driven optimization.',
      videoUrl: 'https://www.youtube.com/watch?v=PqO2aJRqb9M',
      duration: 45,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Paid Advertising & Analytics Lessons
  'sys-chapter-004-4': [
    {
      lessonId: 'sys-lesson-004-4-1',
      chapterId: 'sys-chapter-004-4',
      courseId: 'sys-course-004',
      title: 'Google Ads Fundamentals',
      description: 'Search ads, display network, ad extensions, bidding strategies, and Quality Score.',
      content: 'Master Google Ads to drive targeted traffic and conversions.',
      videoUrl: 'https://www.youtube.com/watch?v=O6qvv0JkSqk',
      duration: 60,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-4-2',
      chapterId: 'sys-chapter-004-4',
      courseId: 'sys-course-004',
      title: 'Facebook Ads Manager',
      description: 'Campaign structure, audience targeting, ad formats, and Facebook Pixel tracking.',
      content: 'Create high-converting Facebook and Instagram ad campaigns.',
      videoUrl: 'https://www.youtube.com/watch?v=fQ-Y8Nef6wM',
      duration: 55,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-4-3',
      chapterId: 'sys-chapter-004-4',
      courseId: 'sys-course-004',
      title: 'Conversion Rate Optimization',
      description: 'Landing page optimization, A/B testing, funnel analysis, and CRO best practices.',
      content: 'Maximize conversions by optimizing every step of the customer journey.',
      videoUrl: 'https://www.youtube.com/watch?v=5G4IIsUxGU0',
      duration: 50,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-004-4-4',
      chapterId: 'sys-chapter-004-4',
      courseId: 'sys-course-004',
      title: 'Google Analytics 4',
      description: 'Track website performance, user behavior, conversions, and create custom reports.',
      content: 'Make data-driven decisions with comprehensive analytics and insights.',
      videoUrl: 'https://www.youtube.com/watch?v=0QlISQ3DH5s',
      duration: 60,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Data Structures & Algorithms Course (Course 005)
  // Algorithm Analysis & Big O Lessons
  'sys-chapter-005-1': [
    {
      lessonId: 'sys-lesson-005-1-1',
      chapterId: 'sys-chapter-005-1',
      courseId: 'sys-course-005',
      title: 'Introduction to Algorithms',
      description: 'What are algorithms, why they matter, and how to analyze algorithm efficiency.',
      content: 'Understand the fundamental concepts of algorithmic thinking and problem-solving.',
      videoUrl: 'https://www.youtube.com/watch?v=0IAPZzGSbME',
      duration: 45,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-1-2',
      chapterId: 'sys-chapter-005-1',
      courseId: 'sys-course-005',
      title: 'Big O Notation Explained',
      description: 'Time and space complexity, O(1), O(n), O(log n), O(n²), and complexity analysis.',
      content: 'Learn to evaluate algorithm performance with Big O notation.',
      videoUrl: 'https://www.youtube.com/watch?v=Mo4vesaut8g',
      duration: 50,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-1-3',
      chapterId: 'sys-chapter-005-1',
      courseId: 'sys-course-005',
      title: 'Best, Average, Worst Case Analysis',
      description: 'Analyze algorithms under different scenarios and understand trade-offs.',
      content: 'Master comprehensive algorithm analysis beyond just Big O.',
      videoUrl: 'https://www.youtube.com/watch?v=FPCWDHbVBvQ',
      duration: 40,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-1-4',
      chapterId: 'sys-chapter-005-1',
      courseId: 'sys-course-005',
      title: 'Recursion & Iteration',
      description: 'Recursive algorithms, base cases, call stack, and converting recursion to iteration.',
      content: 'Understand when to use recursion and how to implement it effectively.',
      videoUrl: 'https://www.youtube.com/watch?v=IJDJ0kBx2LM',
      duration: 55,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Arrays, Linked Lists & Stacks Lessons
  'sys-chapter-005-2': [
    {
      lessonId: 'sys-lesson-005-2-1',
      chapterId: 'sys-chapter-005-2',
      courseId: 'sys-course-005',
      title: 'Arrays & Dynamic Arrays',
      description: 'Array operations, dynamic resizing, two-pointer technique, and sliding window.',
      content: 'Master array manipulation and common array algorithms.',
      videoUrl: 'https://www.youtube.com/watch?v=AT14lCXuMKI',
      duration: 50,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-2-2',
      chapterId: 'sys-chapter-005-2',
      courseId: 'sys-course-005',
      title: 'Linked Lists Deep Dive',
      description: 'Singly linked lists, doubly linked lists, insertion, deletion, and reversal.',
      content: 'Implement and manipulate linked list data structures.',
      videoUrl: 'https://www.youtube.com/watch?v=Hj_rA0dhr2I',
      duration: 55,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-2-3',
      chapterId: 'sys-chapter-005-2',
      courseId: 'sys-course-005',
      title: 'Stacks & Queues',
      description: 'Stack and queue implementation, push, pop, enqueue, dequeue operations.',
      content: 'Learn LIFO and FIFO data structures and their applications.',
      videoUrl: 'https://www.youtube.com/watch?v=wjI1WNcIntg',
      duration: 45,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-2-4',
      chapterId: 'sys-chapter-005-2',
      courseId: 'sys-course-005',
      title: 'Hash Tables & Hash Maps',
      description: 'Hash functions, collision resolution, HashMap operations, and use cases.',
      content: 'Achieve O(1) lookups with hash-based data structures.',
      videoUrl: 'https://www.youtube.com/watch?v=jalSiaIi8j4',
      duration: 50,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Trees & Graphs Lessons
  'sys-chapter-005-3': [
    {
      lessonId: 'sys-lesson-005-3-1',
      chapterId: 'sys-chapter-005-3',
      courseId: 'sys-course-005',
      title: 'Binary Trees & BST',
      description: 'Binary tree traversals (inorder, preorder, postorder), Binary Search Trees.',
      content: 'Work with hierarchical tree data structures.',
      videoUrl: 'https://www.youtube.com/watch?v=fAAZixBzIAI',
      duration: 60,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-3-2',
      chapterId: 'sys-chapter-005-3',
      courseId: 'sys-course-005',
      title: 'Heaps & Priority Queues',
      description: 'Min heap, max heap, heapify, heap sort, and priority queue applications.',
      content: 'Implement efficient priority-based data structures.',
      videoUrl: 'https://www.youtube.com/watch?v=HqPJF2L5h9U',
      duration: 55,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-3-3',
      chapterId: 'sys-chapter-005-3',
      courseId: 'sys-course-005',
      title: 'Graph Representation & Traversal',
      description: 'Adjacency matrix, adjacency list, BFS, DFS, and graph algorithms.',
      content: 'Model and traverse complex relationships with graphs.',
      videoUrl: 'https://www.youtube.com/watch?v=tWVWeAqZ0WU',
      duration: 65,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-3-4',
      chapterId: 'sys-chapter-005-3',
      courseId: 'sys-course-005',
      title: 'Advanced Graph Algorithms',
      description: "Dijkstra's shortest path, Bellman-Ford, Floyd-Warshall, and topological sort.",
      content: 'Solve complex graph problems with advanced algorithms.',
      videoUrl: 'https://www.youtube.com/watch?v=XB4MIexjvY0',
      duration: 70,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Sorting & Searching Algorithms Lessons
  'sys-chapter-005-4': [
    {
      lessonId: 'sys-lesson-005-4-1',
      chapterId: 'sys-chapter-005-4',
      courseId: 'sys-course-005',
      title: 'Sorting Algorithms Fundamentals',
      description: 'Bubble sort, selection sort, insertion sort - understanding basic sorting.',
      content: 'Learn foundational sorting algorithms and their complexity.',
      videoUrl: 'https://www.youtube.com/watch?v=kPRA0W1kECg',
      duration: 50,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-4-2',
      chapterId: 'sys-chapter-005-4',
      courseId: 'sys-course-005',
      title: 'Advanced Sorting Algorithms',
      description: 'Merge sort, quick sort, heap sort - efficient O(n log n) sorting algorithms.',
      content: 'Master efficient sorting techniques used in production systems.',
      videoUrl: 'https://www.youtube.com/watch?v=Hoixgm4-P4M',
      duration: 60,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-4-3',
      chapterId: 'sys-chapter-005-4',
      courseId: 'sys-course-005',
      title: 'Binary Search & Variations',
      description: 'Binary search algorithm, search in rotated arrays, and binary search applications.',
      content: 'Achieve O(log n) search performance with binary search.',
      videoUrl: 'https://www.youtube.com/watch?v=P3YID7liBug',
      duration: 45,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-005-4-4',
      chapterId: 'sys-chapter-005-4',
      courseId: 'sys-course-005',
      title: 'Dynamic Programming',
      description: 'Memoization, tabulation, solving DP problems (fibonacci, knapsack, longest subsequence).',
      content: 'Optimize recursive solutions with dynamic programming techniques.',
      videoUrl: 'https://www.youtube.com/watch?v=oBt53YbR9Kk',
      duration: 70,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Business Strategy Course (Course 006)
  // Strategic Planning & Analysis Lessons
  'sys-chapter-006-1': [
    {
      lessonId: 'sys-lesson-006-1-1',
      chapterId: 'sys-chapter-006-1',
      courseId: 'sys-course-006',
      title: 'Introduction to Business Strategy',
      description: 'What is strategy, competitive advantage, and strategic thinking frameworks.',
      content: 'Understand the fundamentals of business strategy and competitive positioning.',
      videoUrl: 'https://www.youtube.com/watch?v=8DdKZZmFgN8',
      duration: 45,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-1-2',
      chapterId: 'sys-chapter-006-1',
      courseId: 'sys-course-006',
      title: 'SWOT Analysis & Strategic Positioning',
      description: 'Analyze strengths, weaknesses, opportunities, threats, and position your business.',
      content: 'Conduct comprehensive strategic analysis to identify competitive advantages.',
      videoUrl: 'https://www.youtube.com/watch?v=JXXHqM6RzZQ',
      duration: 50,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-1-3',
      chapterId: 'sys-chapter-006-1',
      courseId: 'sys-course-006',
      title: "Porter's Five Forces",
      description: 'Analyze industry competition, bargaining power, threats, and market dynamics.',
      content: "Use Porter's framework to evaluate industry attractiveness and competitive forces.",
      videoUrl: 'https://www.youtube.com/watch?v=mYF2_FBCvXw',
      duration: 55,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-1-4',
      chapterId: 'sys-chapter-006-1',
      courseId: 'sys-course-006',
      title: 'Blue Ocean Strategy',
      description: 'Create uncontested market space, value innovation, and eliminate competition.',
      content: 'Discover how to create new markets instead of competing in existing ones.',
      videoUrl: 'https://www.youtube.com/watch?v=WC_TZ0JIuT0',
      duration: 50,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Business Model Innovation Lessons
  'sys-chapter-006-2': [
    {
      lessonId: 'sys-lesson-006-2-1',
      chapterId: 'sys-chapter-006-2',
      courseId: 'sys-course-006',
      title: 'Business Model Canvas',
      description: 'Nine building blocks: customer segments, value proposition, channels, revenue streams.',
      content: 'Design and innovate business models with the Business Model Canvas framework.',
      videoUrl: 'https://www.youtube.com/watch?v=QoAOzMTLP5s',
      duration: 60,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-2-2',
      chapterId: 'sys-chapter-006-2',
      courseId: 'sys-course-006',
      title: 'Value Proposition Design',
      description: 'Understand customer jobs, pains, gains, and create compelling value propositions.',
      content: 'Craft value propositions that resonate with customer needs.',
      videoUrl: 'https://www.youtube.com/watch?v=ReM1uqmVfP0',
      duration: 50,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-2-3',
      chapterId: 'sys-chapter-006-2',
      courseId: 'sys-course-006',
      title: 'Revenue Streams & Pricing',
      description: 'Pricing strategies, subscription models, freemium, and revenue optimization.',
      content: 'Design profitable revenue models and pricing strategies.',
      videoUrl: 'https://www.youtube.com/watch?v=Q8CrjHzp7A4',
      duration: 55,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-2-4',
      chapterId: 'sys-chapter-006-2',
      courseId: 'sys-course-006',
      title: 'Platform Business Models',
      description: 'Network effects, multi-sided platforms, and ecosystem strategies.',
      content: 'Understand how platform businesses create value through network effects.',
      videoUrl: 'https://www.youtube.com/watch?v=01TG_D_N8RA',
      duration: 50,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Leadership & Team Management Lessons
  'sys-chapter-006-3': [
    {
      lessonId: 'sys-lesson-006-3-1',
      chapterId: 'sys-chapter-006-3',
      courseId: 'sys-course-006',
      title: 'Leadership Styles & Effectiveness',
      description: 'Transformational, transactional, servant leadership, and situational leadership.',
      content: 'Develop your leadership style and adapt to different situations.',
      videoUrl: 'https://www.youtube.com/watch?v=VBod_0KB0yg',
      duration: 50,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-3-2',
      chapterId: 'sys-chapter-006-3',
      courseId: 'sys-course-006',
      title: 'Team Building & Culture',
      description: 'Build high-performing teams, foster collaboration, and create positive culture.',
      content: 'Create teams that execute strategy effectively and maintain high morale.',
      videoUrl: 'https://www.youtube.com/watch?v=eRaUQlsK1bk',
      duration: 45,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-3-3',
      chapterId: 'sys-chapter-006-3',
      courseId: 'sys-course-006',
      title: 'Change Management',
      description: "Manage organizational change, overcome resistance, and implement Kotter's 8 steps.",
      content: 'Lead successful organizational transformations and change initiatives.',
      videoUrl: 'https://www.youtube.com/watch?v=pYKH2uSax8U',
      duration: 55,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-3-4',
      chapterId: 'sys-chapter-006-3',
      courseId: 'sys-course-006',
      title: 'Performance Management',
      description: 'Set goals, track KPIs, provide feedback, and conduct performance reviews.',
      content: 'Manage team performance to achieve strategic objectives.',
      videoUrl: 'https://www.youtube.com/watch?v=3kCgMKfWk5k',
      duration: 50,
      order: 4,
      isSystemContent: true,
    },
  ],

  // Growth & Scaling Strategies Lessons
  'sys-chapter-006-4': [
    {
      lessonId: 'sys-lesson-006-4-1',
      chapterId: 'sys-chapter-006-4',
      courseId: 'sys-course-006',
      title: 'Growth Strategy & Market Expansion',
      description: 'Market penetration, development, product development, and diversification strategies.',
      content: 'Plan and execute growth strategies to scale your business.',
      videoUrl: 'https://www.youtube.com/watch?v=lhZJJqKEFng',
      duration: 55,
      order: 1,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-4-2',
      chapterId: 'sys-chapter-006-4',
      courseId: 'sys-course-006',
      title: 'Mergers & Acquisitions',
      description: 'M&A strategy, due diligence, valuation, and post-merger integration.',
      content: 'Understand how companies grow through strategic acquisitions.',
      videoUrl: 'https://www.youtube.com/watch?v=t8uxJ9B1R3I',
      duration: 60,
      order: 2,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-4-3',
      chapterId: 'sys-chapter-006-4',
      courseId: 'sys-course-006',
      title: 'Financial Planning & Fundraising',
      description: 'Financial modeling, investor pitch decks, venture capital, and bootstrapping.',
      content: 'Secure funding and manage finances to support growth.',
      videoUrl: 'https://www.youtube.com/watch?v=jQO2pUKdQ44',
      duration: 65,
      order: 3,
      isSystemContent: true,
    },
    {
      lessonId: 'sys-lesson-006-4-4',
      chapterId: 'sys-chapter-006-4',
      courseId: 'sys-course-006',
      title: 'Strategic Execution & Monitoring',
      description: 'Balanced scorecard, OKRs, strategy implementation, and performance tracking.',
      content: 'Execute strategy effectively and monitor progress toward goals.',
      videoUrl: 'https://www.youtube.com/watch?v=L4N1q4RNi9I',
      duration: 55,
      order: 4,
      isSystemContent: true,
    },
  ],
};
